version: "3.9"

services:

  go:
    container_name: go
    build: 
      context: ../go/
      dockerfile: ./Dockerfile
      args:
        - PLATFORM=$CPU_ARCH
    environment: 
      - TMP=/home/tom/code/tmp/
    volumes: 
      - ${PROJECT_DIR}/:/home/tom/code/dev/app/
      - ${PROJECT_DIR}/github/thomasreulen/aws/cdk/go/:/home/tom/code/go/
      - ${AWS_CREDENTIAL_DIR}:/root/.aws

  ubuntu:
    container_name: ubuntu    
    build: 
      context: ../ubuntu/
      dockerfile: ./Dockerfile
      args:
        - PLATFORM=$CPU_ARCH
    command: tail -F anything      
    volumes: 
      - ${PROJECT_DIR}/:/home/tom/code/
      - ${AWS_CREDENTIAL_DIR}:/root/.aws
      - ${KUBE_CONFIG_DIR}:/root/.kube
      - /var/run/docker.sock:/var/run/docker.sock

  cdk:
    container_name: cdk
    build: 
      context: ../cdk/
      dockerfile: ./Dockerfile
      args:
        - PLATFORM=$CPU_ARCH
    command: tail -F anything      
    volumes: 
      - ${PROJECT_DIR}/:/home/tom/code/
      - ${AWS_CREDENTIAL_DIR}:/root/.aws
      - ${KUBE_CONFIG_DIR}:/root/.kube
      - /var/run/docker.sock:/var/run/docker.sock

  amplify:
    privileged: true
    container_name: amplify
    build: 
      context: ../node/
      dockerfile: ./Dockerfile
      args:
        - PLATFORM=$CPU_ARCH
    environment:
      - NODE_ENV=devleopment
    working_dir: /home/node/app
    volumes:
      - ${AWS_CREDENTIAL_DIR}:/root/.aws
      - ${PROJECT_DIR}/github/thomasreulen/aws/amplify/react-tutorial:/home/node/app/      
      - nodemods-amplify:/home/node/app/node_modules:rw
    restart: always
    command: [ "tail", "-F", "anything" ]
    ports:
      - 3000:3000
      - 20002:20002

   
volumes:
  nodemods-amplify: